# Playbook template
---
- name: Playbook template
  hosts: "{{ host }}"
  become: True

  tasks:
    - name: Creating user
      ansible.builtin.user:
        name: "{{ username }}"
        shell: /sbin/nologin